In [5]:
import sys
import numpy as np

In [6]:
a = np.array([1,2,3,4])

In [7]:
b = np.array([0,.5,1,1.5,2])

In [8]:
b[0],b[2], b[-1]

(0.0, 1.0, 2.0)

In [9]:
b[[0,2,-1]]

array([0., 1., 2.])

In [10]:
c = np.array([0.5,3.5,4.66])

In [11]:
c.dtype

dtype('float64')

In [12]:
c.dtype = np.float32

In [13]:
c.dtype

dtype('float32')

 NumPy in Multidimensional Arrays

In [14]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [15]:
A.shape

(2, 3)

In [16]:
A.ndim

2

In [17]:
A.size

6

In [18]:
B = np.array([
    [
        [12,11,10],
        [9,8,7]
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [19]:
B.size

12

In [20]:
B.shape

(2, 2, 3)

In [21]:
B.ndim

3

In [22]:
B[0]

array([[12, 11, 10],
       [ 9,  8,  7]])

In [23]:
B[1,0]

array([6, 5, 4])

Indexing and Slicing of Matrices

In [24]:
Arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [25]:
Arr[1]

array([4, 5, 6])

In [26]:
Arr[1,0]

4

In [27]:
Arr[0,2]

3

In [28]:
Arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
 Arr.sum

<function ndarray.sum>

In [30]:
Arr.sum()

45

In [31]:
Arr.mean().dtype

dtype('float64')

In [32]:
Arr.mean()

5.0

In [33]:
Arr.sum(axis=0) #columnwise sum

array([12, 15, 18])

In [34]:
Arr.mean(axis=0) #Columnwise mean

array([4., 5., 6.])

In [35]:
Arr.sum(axis=1) #Rowwise sum

array([ 6, 15, 24])

In [36]:
Arr.mean(axis=1)

array([2., 5., 8.])

In [37]:
Arr.std()

2.581988897471611

In [38]:
Arr.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [39]:
Arr.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

 Broadcasting and Vectorized Operations

In [40]:
a = np.arange(4)

In [41]:
a

array([0, 1, 2, 3])

In [42]:
a+10

array([10, 11, 12, 13])

In [43]:
a*10

array([ 0, 10, 20, 30])

In [45]:
a

array([0, 1, 2, 3])

In [46]:
l = [0,1,2,3]

In [47]:
[i*10 for i in l]

[0, 10, 20, 30]

Boolean Arrays (Also called masks)

In [48]:
b = np.arange(4)

In [49]:
b

array([0, 1, 2, 3])

In [50]:
b[0],b[-1]

(0, 3)

In [52]:
b[[True,True,False,True]]

array([0, 1, 3])

In [53]:
b>=2

array([False, False,  True,  True])

In [54]:
b[b>=2]

array([2, 3])

In [55]:
b[b<=b.mean()]

array([0, 1])

In [56]:
A = np.random.randint(100,size=(3,3))

In [57]:
A

array([[65, 99, 92],
       [60,  9, 93],
       [11, 56, 54]])

In [58]:
A>30

array([[ True,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [59]:
A[A>30]

array([65, 99, 92, 60, 93, 56, 54])

In [60]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [61]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [63]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [64]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [65]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [66]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [68]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [70]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

In [71]:
import pandas as pd
import numpy as np

In [72]:
g7_pop = pd.Series([35.467,63.951,80.940,60.665,127.061,64.511,318.523])